image: itxtech/docker-env-tstar

stages:
 - package

phar:
  stage: package
  script:
   - sed -i "s/const VERSION \?= \?\"\(.*\)\"/const VERSION = \"\1$([ ${CI_BUILD_REF_NAME} != master ] && echo unsupported-)${CI_BUILD_REF:0:7}\"/" src/pocketmine/PocketMine.php
   - sed -i "/GIT_COMMIT/s/0000000000000000000000000000000000000000/${CI_BUILD_REF}/" src/pocketmine/PocketMine.php
   - ./tests/ci.sh
   - mv plugins/T-STAR-DevTools_OUTPUT/t-STAR*.phar .
  artifacts:
    paths:
     - T-STAR*.phar

